// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

/* templ GOLPage() {

<body class="bg-gray-200 h-screen w-screen m-0 p-0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" />
    <script src="/static/gol.js" defer></script>
    <div class="flex flex-col h-full">
        @Header()
        <div class="flex-grow grid justify-items-center items-center">
            <canvas class="border border-black m-0 p-0 box-border w-full h-full" id="gameCanvas"></canvas>
            <div class="flex justify-between w-full px-4">
                <div class="flex space-x-2">
                    <button class="px-4 py-2 border border-gray-700 bg-gray-300 rounded-md" onclick="startGame()">Start</button>
                    <button class="px-4 py-2 border border-gray-700 bg-gray-300 rounded-md" onclick="stopGame()">Stop</button>
                </div>
                <input type="file" id="fileInput" accept=".txt" />
                <div class="text-xl mt-3" id="generationCounter">Generation: 0</div>
            </div>
        </div>
    </div>
</body>
} */

func GOLPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"bg-gray-200 h-screen w-screen m-0 p-0\"><link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\"><script src=\"/static/gol.js\" defer></script><div class=\"flex flex-col h-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- This div acts as the flex container for the canvas and buttons --><div class=\"flex-grow flex flex-col items-center justify-center\"><!-- Canvas that grows to fill all available space --><canvas class=\"border border-black m-0 p-0 w-full h-full\" id=\"gameCanvas\"></canvas><!-- Buttons aligned below the canvas --><div class=\"flex justify-between w-full p-4\"><div class=\"flex space-x-2\"><button class=\"px-4 py-2 border border-gray-700 bg-gray-300 rounded-md\" onclick=\"startGame()\">Start</button> <button class=\"px-4 py-2 border border-gray-700 bg-gray-300 rounded-md\" onclick=\"stopGame()\">Stop</button></div><input type=\"file\" id=\"fileInput\" accept=\".txt\"><div class=\"text-xl mt-3\" id=\"generationCounter\">Generation: 0</div></div></div></div></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
