// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Header() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header id=\"header\" class=\"bg-gray-800 text-white p-4 flex justify-between items-center\"><div class=\"flex items-center space-x-4\"><a href=\"/home\" class=\"text-lg font-bold\">Workshop</a> <button onclick=\"history.back()\" class=\"px-4 hover:bg-gray-600 bg-gray-700 py-2 rounded-md\">Back</button></div><nav class=\"space-x-4\"><a href=\"/projects\" class=\"px-4 hover:bg-gray-600 bg-gray-700 py-2 rounded-md\">Projects</a> <a href=\"/learn\" class=\"px-4 hover:bg-gray-600 bg-gray-700 py-2 rounded-md\">Learn</a> <a href=\"/data\" class=\"px-4 hover:bg-gray-600 bg-gray-700 py-2 rounded-md\">Data</a> <a href=\"/about\" class=\"px-4 hover:bg-gray-600 bg-gray-700 py-2 rounded-md\">About</a></nav></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
