// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Home() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"bg-gray-400\"><link rel=\"icon\" href=\"/static/favicon.ico\" type=\"image/x-icon\"><script src=\"https://unpkg.com/htmx.org@1.9.10\" integrity=\"sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC\" crossorigin=\"anonymous\"></script><link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.18/dist/tailwind.min.css\" rel=\"stylesheet\"><div class=\"mx-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"min-h-screen flex flex-col\"><div class=\"flex-1 bg-blue-200\" style=\"height: 50vh;\"><div class=\"text-xl font-bold text-white p-5\">Dashboard Area</div><div class=\"p-5 text-white\">Content that you can customize for tracking various metrics or statuses.</div></div><div class=\"flex w-full\" style=\"height: 50vh;\"><div class=\"w-1/2 bg-green-200 p-5\"><div class=\"text-xl font-bold\">Projects</div><ul class=\"list-disc list-inside\"><li class=\"my-3\"><a class=\"p-1 bg-green-300 hover:bg-green-400 rounded-md\" href=\"/projects/flashcard\">Flashcards</a></li><li class=\"my-3\"><a class=\"p-1 bg-green-300 hover:bg-green-400 rounded-md\" href=\"/projects/flashcard/random\">Random Flashcard</a></li><li class=\"my-3\"><a class=\"p-1 bg-green-300 hover:bg-green-400 rounded-md\" href=\"/projects/gol\">Game of Life</a></li></ul></div><div class=\"w-1/2 bg-red-200 p-5\"><div class=\"text-xl font-bold\">Transactions</div><ul class=\"list-disc list-inside\"><li>Transaction 1</li><li>Transaction 2</li><li>Transaction 3</li></ul></div></div></div></div></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
